### PR TITLE
July Design Update

### PR DESCRIPTION
**Pull request by garrying**
## Fixes
- [x] Fix open call events button overlapping on mobile

## Features
- [x] Mention TMAC venue
- [x] Add something about registration launching in august
- [ ] Add in vector clip-art assets (Deferred to later)
- [x] Something something organizer order, did something silly here => https://github.com/ournetworks/ournetworks.ca/pull/115/commits/c54a6bc2c01f249e49185cf5df4cc1f882b9d9fd

### CODE REVIEW

**Comment by dcwalk** [comment]
(just moved the todos that didn't get done in #102)

**Comment by dcwalk** [comment]
@garrying tried to do all the bits here, can we do a quick review and merge in the next day or so?

**Comment by garrying** [comment]
The randomizer seemed stuck. I swapped the `date` reference to unix epoch in 6a94818

**Comment by dcwalk** [comment]
Thanks! I went through a few tries on best ways to try to implement
randomize on regen. Learned all the ways I wish Liquid was different a bit
😭

**Pull request merged**
