### PR TITLE
Made all the <h1> tags bold

### PR DESCRIPTION
**Pull request by Shrinks99**
This improves the readability of the hero text and also introduces better hierarchy for the other pages.

Here's a preview of what that looks like on the homepage
screen shot 2018-05-09 at 1 41 21 pm

and on a text page
screen shot 2018-05-09 at 2 13 00 pm

### CODE REVIEW

**Comment by dcwalk** [comment]
Hey @Shrinks99 thanks for submitting!

I find the weight we have more readable with this typeface. Also I'm inclined to find size+line spacing enough to establish a flow on headings that feels legible. As a result, I'd hesitate to make the change as I see the current version as accomplishing the same ( and probably more inline with my preference 🦑 ).

Anyway, I'll ask @garrying to weigh in and trust his judgement as he worked with Marlo to establish the design concept.

**Comment by Shrinks99** [comment]
¯\\\_(ツ)_/¯ If everyone agrees then hey, maybe I'm wrong.  Personally I find adding one more element of hierarchy with type (in addition to the size) helps with picking out key information and separating different information.  Also Cotham Sans is a bit of a weird font but I like it!  The kerning could probably be improved in some areas (see the "two" in "Networks" where the 'W' is sort of awkwardly spaced :P ) which will be more apparent in the bold version.

**Comment by garrying** [comment]
@Shrinks99 Thanks for taking a look at this! I'd like to keep to using size and vertical spacing for Cotham Sans because its quirks seem more resolved at normal weight. Open to suggestions on size/vertical spacing for the homepage block. The headings on other pages seem ok as is.

**Comment by Shrinks99** [comment]
I will play around with the spacing a little bit instead.  If I come up with anything I think is better I will resubmit it as a new PR.

**Pull request closed without merging**
