### PR TITLE
Add From Learning To Building Networks sprint

### PR DESCRIPTION
**Pull request by benhylau**

### CODE REVIEW

**Review by dcwalk — COMMENTED** [review]
So is the idea that this sprint lasts only for the one day? (Monday 2 hours)

I think maybe you want to provide a bigger window, usually sprints are frames around a project, and distinct activities are broken out (e.g., tomesh is the sprinting, Monday is: workshop; Tues-Wed is graphana, website revamp, etc....) 

As I read this the hope is to review the workshop at tpl and then brainstorm the hook from that to other things?

**Comment by dcwalk** [comment]
Hey @benhylau just looping back on this, would merging in shortly work?

**Comment by benhylau** [comment]
I cannot commit to doing a 2-3 day at this point. Let's merge this in for now and update later if the format changes?

**Comment by dcwalk** [comment]
That's fine, this is specified for 2 hours on Monday, is that the amt of time you want?

**Comment by benhylau** [comment]
Yes for now, if there is more interest throughout the conference we can extend the length.

**Comment by dcwalk** [comment]
Okay, merging in

**Pull request merged**
