### PR TITLE
Add redirect plugin, and redir from /cfp to front

### PR DESCRIPTION
**Pull request by patcon**
Ticketed from: https://github.com/ournetworks/2018/issues/9#issuecomment-368616105

No presh.

### CODE REVIEW

**Comment by dcwalk** [comment]
I think this has potential, just flagging that you'll need to add yourself as a contributor in the README @patcon :)

**Comment by dcwalk** [comment]
Hey @patcon, per convo in #6 can we move the 
```
redirect_from:
  - '/cfp'
```
to **2018**?

**Comment by dcwalk** [comment]
I'm happy to do, just just didn't wanna step on yr toes!

**Comment by patcon** [comment]
Done and done! Ready

**Review by dcwalk — APPROVED** [review]
🙏 nice!

**Pull request merged**
