### PR TITLE
Add in 2017 banner in preperation for 2017 archived site

### PR DESCRIPTION
**Pull request by dcwalk**
This moves us closer to https://github.com/ournetworks/2018/issues/125, and builds off of  https://github.com/ournetworks/ournetworks.ca/commit/8bed6677c49b813896ce05ddcec4cd9e275a9c3e

Things changed:

- added banner 
- removed volunteering call out from the bottom
- switched to the new favicon

screen shot 2018-10-23 at 12 50 12 pm

The part that I'm a little unsure about is the best way to merge this into master (!!) for tagging.

### CODE REVIEW

**Comment by garrying** [comment]
@dcwalk I cherry-picked a commit to fix an issue with button styling, and adjusted the banner styling. I think this is good to be tagged. Maybe you could give it one more review with my changes?

Thinking we don't merge this into `master`; we can tag from the last commit in this branch and close this PR (and delete this branch). I tried it in another repo it kept the tagged version.

**Comment by dcwalk** [comment]
@garrying this looks great! I'm so sorry for letting this hang. I'm happy with your strategy to  tag, close PR, then delete the branch (aii!)

Wanna do the honours? Or I will end of this week :)

**Comment by dcwalk** [comment]
Okay, it looks like we have a release here: https://github.com/ournetworks/ournetworks.ca/releases/tag/2017

I'm closing this PR for now, we should track progress (or issues) in https://github.com/ournetworks/2018/issues/125

**Comment by garrying** [comment]
Updated https://2017.ournetworks.ca

**Pull request closed without merging**
