### PR TITLE
Updated Recorded Talks Page

### LINKED ISSUE #155: Speaker names not rendering on recorded talks page
https://ournetworks.ca/recorded-talks/ if viewing through the root domain.

### LINKED ISSUE #157: Incorrect share link when playing a live archive
The share bar on [live player](https://ournetworks.ca/livestream/) needs to show the m3u8 file that is passed thru url param, if one is passed, instead of generating a current one.

### PR DESCRIPTION
**Pull request by garrying**
## Fixes
- [x] Fixes #157
- [x] Revised session video include to support multiyear sessions → 4bb46ef
  - Fixes https://github.com/ournetworks/ournetworks.ca/issues/155
- [x] Resolves an issue with bundler 2 in Travis → 8fa87c0

## Features
- [x] #154 
- [x] Add 2019 section to `/recorded-talks`
  - Note: 2019.ournetworks.ca was manually built from this branch. It should be updated once this branch has been merged
- [x] Add `Recorded Talks` back to the site navigation
- [x] Add IPFS links
- [x] Add YouTube links
  - [x] Add YouTube playlist
- [x] Add `loading="lazy"` attribute to `` on `/recorded-talks`
- [x] Add livestream archive links
  >https://2019.ournetworks.ca/livestream/?m3u8=live-2019-09-20.m3u8
  >https://2019.ournetworks.ca/livestream/?m3u8=live-2019-09-21.m3u8
  >https://2019.ournetworks.ca/livestream/?m3u8=live-2019-09-22.m3u8

### CODE REVIEW

**Comment by benhylau** [comment]
This looks good. #154 now targets this branch, and I made a minor adjustment in my PR here https://github.com/ournetworks/ournetworks.ca/pull/154/commits/c03c2d23ee745141f2dc84b6cb02170fd5f921dd#diff-aeb42283af8ef8e9da40ededd3ae2ab2R17 to:

- Remove the `ipfs` from the gateway and added it to the templates (since it's part of the protocol not the gw itself, otherwise we can't use the param for ipns)
- Use ipfs.io as gateway

I suggest you check the ipfs.io gateway performance before merging. I am in an area without good internet, so everything plays choppy to me :)

**Comment by garrying** [comment]
@benhylau Two thoughts after merging #154:
- Does it make sense to hide the share controls on `/video`? My suggestion: 27cdcb8
- The livestream links start at the end of stream rather than the start. Is there a way to have them start from the beginning?

**Review by benhylau — APPROVED** [review]
Approved, aside from https://travis-ci.com/ournetworks/ournetworks.ca/builds/141705862#L455

**Review by ana0 — APPROVED** [review]

**Comment by Shrinks99** [comment]
I know I wasn't asked to review this but there seems to be a slight issue with how multiple screen sizes are supported on the recorded talks list page.  When the webpage is viewed at a small width the page does not resize properly which seems to be because links are not inheriting the size of their parent container because those links are long!  
Screen Shot 2019-12-26 at 10 37 38 PM

Adding `word-wrap: break-word;` to the <a> tag fixes this issue so we won't have a weird sideways scroll bar on mobile.

Other than that, I have tested both the livestream archive and this page and they seem to be good to go!

**Pull request merged**
