### PR TITLE
Add Recorded Talks page

### PR DESCRIPTION
**Pull request by dcwalk**
Partially addressing https://github.com/ournetworks/2018/issues/87. This is roughed out with:

- [x] 2 links in sessions yml (ipfs and youtube link)
- [x] update to announcement
- [x] new page which will display, sorted by name, all the videos from 2018.
- [x] final links in sessions yml for data files
- [x] clean up how those links are displayed (`_includes`)
revised TODOs based on Sat 29 convo:
- [x] switch to two column view
- [x] add thumbnail for video and restructure links
- add in icons for 
  - [x] youtube 
  - [x] ipfs?
- [x] add link to ipfs hashes and full archive
- (eventually) add links to internet archive

### CODE REVIEW

**Comment by benhylau** [comment]
We should be able to modify our static IPFS player we used for the live stream to play an IPFS hash off of ipfs.io gateway. Want to me add that page instead?

cc. @darkdrgn2k

**Comment by dcwalk** [comment]
can we embed something like that on the page @benhylau? 

If not, I think we should explore whatever you are imagining as a later stage improvement (there will still be refinements to the web page to bring it into "archive" state after this PR is merged...

**Comment by benhylau** [comment]
Yea it'd be an embed, so we link from schedules to a page like https://ournetworks.ca/livestream/
If that is the UX we want I should be able to do this before Thursday. We'd have a dependency on ipfs.io gateway being available, but do not require our own backends.

**Comment by dcwalk** [comment]
Hey @garrying and @benhylau --

 I was thinking (getting fancy) that we might want to have a thumbnail for the click to play on ipfs player, is there an easy way to do that with just the player? the pattern of a youtube (any streaming video service embed) is what I have in mind

A alternative is to get the assets from hank for the youtube videos and add those to the data file, but that does not seem like a good pattern future forward.

**Comment by garrying** [comment]
re thumbnails: We could use YouTube's thumbnails through this asset url pattern: `https://img.youtube.com/vi/{{ linkYoutube }}/maxresdefault.jpg`

**Comment by Shrinks99** [comment]
@garrying All the thumbnails are included in the project delivery files.  If you want them I can send them all over!

**Comment by benhylau** [comment]
Can we also add AV team recognition to bottom of `recorded-talks` page? Basically in a single line in this order:

[Yurko Jaremko](https://github.com/darkdrgn2k), [Henry Wilkinson](https://github.com/Shrinks99), [Elon Li](https://github.com/ASoTNetworks), [Benedict Lau](https://github.com/benhylau)

@darkdrgn2k @Shrinks99 @ASoTNetworks you guys cool with using full names (consistent with [how organizers are listed](https://ournetworks.ca/about/)) + linking to GitHub?

**Comment by Shrinks99** [comment]
I don't know about Yurko but I've spoken to Elon and he's cool with it as am I.

**Comment by dcwalk** [comment]
I added the acknowledgements to the top line already, do you want it moved
to the bottom?

**Comment by benhylau** [comment]
Oops didn't see. @dcwalk how do you feel about linking to GitHub and reorder?

**Comment by benhylau** [comment]
Do we prefer linking to the hash `QmPk33q8z8GHhJoDKXGDGn5CWFu61TzTprgupfGe4VNwho` or `Qmc98oo4qdiUQniHjWu2wknaRgPD3JgfHtPvjngcxLLmuY/720p/Our_Networks_2018_Aether_Distributing_Social_Networks_Without_Distributed_Consensus_by_Burak_Nehbit_720p.mp4`? The player should handle both.

**Comment by dcwalk** [comment]
@benhylau I think just the hash would be more manageable and fit how we set up the links in the data file.

**Comment by dcwalk** [comment]
Okay, getting closer.... still some bad layout issues that need some design care (see below)
screen shot 2018-09-30 at 3 08 33 pm

**Comment by dcwalk** [comment]
We have talked about adding the ipfs logo in front to help differentiate it from youtube,
https://github.com/ipfs/logo/blob/master/vector/ipfs-logo-vector-black.svg

screen shot 2018-09-30 at 3 22 55 pm


Looking at it, I'm honestly not sure if it helps wayfinding/clarifying. Thoughts?

**Comment by benhylau** [comment]
screen shot 2018-10-01 at 1 04 32 am

- Put the three locations in a code block ```?
- This first line should have `IPFS: `
- `s/Youtube/YouTube` and remove the `playlist` at end of line
- I don't like the `s/stream/video` change and the `Video Player` as title, maybe `s/stream/recorded` or keep `stream` and `Recorded Video`?
- Thumbnails (and perhaps IPFS link as well) should both link to https://ournetworks.ca/stream/?ipfs=QmRvHxC16K1hqeWdmtGNQQ6jnogq9pfmbVo4VSZqeET8dE
- Since we have thumbnails we should remove the title text for each video, it makes things less searchable but now it looks unnecessarily crowded and redundant

**Comment by Shrinks99** [comment]
Fixed `local-networks` thumbnail available [here](https://www.dropbox.com/s/9xvkuuikyrtgjym/thumbnail.png?dl=0).

**Comment by dcwalk** [comment]
@Shrinks99 can you upload that to youtube? that is where we are pulling these from

**Comment by Shrinks99** [comment]
@dcwalk Already done!  It may take a bit to propagate and fix on your end but YouTube has the right file.

**Comment by dcwalk** [comment]
I reverted the links below to be "external" (and indicate one as HD?) also added the ipfs icon (whoopie), kinda looks nice ghostly-like.

I'm sort of ready to launch this and have us tweak the thumbnail look later..

I was thinking we could like have a transparent dark overlay and a play button all video player like?
That would visually distinguish it from the text, make clear it is clickable, etc...

I don't have time on this until tomorrow evening tho, and if it is critical pre-email than we should sit on it?

**Comment by benhylau** [comment]
The `HD` can be by itself instead of the double icon, which messes up alignment.

**Comment by garrying** [comment]
I'll follow up on adding the hover overlay tonight.

**Comment by Shrinks99** [comment]
Thumbnails have all been fixed and uploaded to YouTube as specified in the chat by @dcwalk.

**Comment by garrying** [comment]
Exiting WIP. There are a few noticeable changes:
- Fixed the IPFS icon (Weird SVG grouping issue was causing the original ghost look)
- Added the play overlay in dfb9278 (the overlay behaviour could be reversed)
- Added border to distinguish the links from the description

**Comment by dcwalk** [comment]
That overlay looks beautiful `fake-player` 😍 

screen shot 2018-10-01 at 10 18 38 pm

**Comment by dcwalk** [comment]
I wish I could review my own PR.... basically 👍 LGTM!

**Review by ana0 — APPROVED** [review]

**Comment by Shrinks99** [comment]
I know nowadays 720p isn't exactly super large but _both_ of the resolutions we have published do qualify as high definition.  I think listing resolutions as `1080p` and `720p` buttons instead of 'HD'  would be a better fit.
(also the 1080p file is pretty high bitrate and not really meant for streaming, more meant for downloading)

Other than that I like it a lot!  You have all gone above and beyond here, I'd be shocked to find another conference that hosts their own video distribution network, especially using bleeding edge protocols and does it as nicely as this.

EDIT: SVGs of these maybe?  (I have SVGs and if you want to use them I'll send 'em over!)

**Comment by benhylau** [comment]
Agree with @Shrinks99 about the HD part, I also felt it was a mislabel (people would wanna watch the HD assuming the other one is poor quality) but between 720p and 1080p definitely 720p! Also important because our 1080p are not only HD, they are digital masters that are 3-4x the size of the 720p streams! Having both labeled also fix our weird misalignment issues with extra icon.

**Comment by Shrinks99** [comment]
[720p Button Dropbox Link](https://www.dropbox.com/s/6nx9dno0ic6a2xc/720.svg?dl=0)

[1080p Button Dropbox Link](https://www.dropbox.com/s/k9suojqm2vhl1qx/1080.svg?dl=0)

Would have done PRs and been proper but I've got class and I know we're rushed for time.  Hopefully this is okay, these will be deleted from Dropbox once they're added to the repo (if y'all decide to do that).

**Comment by dcwalk** [comment]
Thanks folks, the issue with trying to indicate 720/1080 is it is hard to find an icon that is legible at that small size. I went through a bunch of testing before settling on the `HD` one, in part because that one is used for 1080 (there is some classification schema that has a different way to showing 720... not just the HDready as TVs do).

Anyway, tried with your icons a few ways Han and the same issue... can't tell they are different.

screen shot 2018-10-02 at 9 31 19 am

In the interest of getting this out the door, I've reverted to monospace text as that apparently meets the requirements:
- differentiate 720/1080
- does not change alignment

This is hacky and should be changed, but it is so minor I figure we can do so on the fly.
screen shot 2018-10-02 at 9 29 24 am

As we've all looked at it and this was the only feedback (and I've got us to an uneasy resolution), lets meeeerrrrrrgggggggeeeeeee?

**Comment by benhylau** [comment]
I have made a one-line change to use `ipfs.infura.io` because they have awesome gateway bandwidth and stability. I left all other links pointing to `ipfs.io` because that is where we pin, and we treat that as "origin" of our archives.

**Review by benhylau — APPROVED** [review]

**Comment by Shrinks99** [comment]
Whoop, should have tested the buttons.  Doing it with text is good!

**Pull request merged**
