### PR TITLE
Notification change for successful builds

### PR DESCRIPTION
**Pull request by garrying**
@patcon following up on #7: My thinking is that we'd want to know of failed builds/test over successful ones to keep notifications light for those on `orga`

### CODE REVIEW

**Comment by dcwalk** [comment]
I'm fine with this @garrying , is the reason the PR is failing because of setting the base URL we experienced from the other issue?

(error is `The command "bundle exec htmlproofer --check-html --internal_domains /www.ournetworks.ca/,/ournetworks.ca/ ./_site" failed. Retrying, 3 of 3.`)

**Review by patcon — CHANGES_REQUESTED** [review]
I recommend:

```yml
on_failure: change
on_success: change
```

Then we get an email once when it first breaks, and another when it gets fixed. Turning it off wholesale means that someone can't tell from their inbox if a fix happened yet :)

**Comment by patcon** [comment]
Also, http://karenlouisesmith.net/ is struggling. We can prob add it to an ignore list for now

cc: @smithisgeneric

**Comment by patcon** [comment]
Pre-visited website, and then reran travis, and it passed :)

**Comment by dcwalk** [comment]
+1 with @patcon's take :)

**Comment by garrying** [comment]
@patcon recommendation sounds good. gonna merge

**Pull request merged**
