### PR TITLE
Set up site for 2019 ournets

### PR DESCRIPTION
**Pull request by dcwalk**
This is the start of bringing back the site to neutral in advance of the 2019 call going out!

- [x] remove 2018 content
- [x] reset main splash
- [x] modify pages that will stick around (swag, about, visiting, recorded talks)
- [x] update nav message
- [x] dec'n about feeback page? -- i deleted, we kept/update a copy that is served on the 2018 site
- [x] swag/donate/support? -- changed into a support page based on Jan-15 convo
- [x] style tweaks
- [x] link testing!

from review:
- [x] remove nav announcement
- [ ] add mention of twitter
- [x] update IA in nav

### CODE REVIEW

**Comment by dcwalk** [comment]
Okay @garrying I think I've done a first draft of structure and content that reflects what a 2019 version should look like. Merged in master after the 2018 version was deployed.

Over to you for review!

**Comment by dcwalk** [comment]
Okay @garrying I think I've done a first draft of structure and content that reflects what a 2019 version should look like. Merged in master after the 2018 version was deployed.

Over to you for review!

**Comment by garrying** [comment]
@dcwalk I think this looks good. Three thoughts:
- Would it make sense to mention our twitter as another place to get updates? Could be an inline mention or maybe there's another place
- With the menu links, thinking 2017 could be last? Keeping the two year links closer to each other
- The announcement banner link to videos and the link in the menu seem a bit redundant. Maybe the banner is not needed given the messaging in the splash?

**Comment by dcwalk** [comment]
@garrying -- I'm not sure I'm following your sense of the Top Nav, can you mock up / write out?

**Comment by dcwalk** [comment]
Agree about removing banner, I tried but not sure if the splash spacing adjustments are appropriate

**Comment by garrying** [comment]
@dcwalk Reordering the navigation. Feel free to revert. Mocked up in 5e79ab0dad6793a776d6fd081f65fc92757d0e24:
screen shot 2019-01-19 at 9 30 20 pm

**Comment by garrying** [comment]
Revised the years to be in a dropdown in 55e735d. @dcwalk I think it feels more resolved. Good to merge? or do we want to include twitter mention in this PR?

**Comment by dcwalk** [comment]
I dig it! Let's merge so we don't let this linger? 

I just spent some time muttering about Twitter, think it isn't major but I also wasn't seeing a clear resolution. Filing an issue in #89 to keep us accountable

**Pull request merged**
