### PR TITLE
Added specific call-out to clarify open nature of call

### PR DESCRIPTION
**Pull request by patcon**
Am I understanding correcrly that less technical people are welcome (ie. ppl never having done networking tech? or perhaps no more than wordpress dev? or perhaps any tech at all)?

If so, I wonder whether we can explicitly call-out some various participant "types" (technical and otherwise) that we'd like to show up. The copy is so so clear in many ways, but I'm now about to send it out via Twitter with fresh eyes, and I'm wondering if someone might still read this assuming it's only for deeply technical people :)

Can someone else suggest the "outlier" people -- professions, roles, etc. -- that they hope to show up? I have my own sense, but I'm not 100% sure that I'm imagining it correctly...!

### CODE REVIEW

**Review by benhylau — CHANGES_REQUESTED** [review]
That information is already on the CfP page: https://ournetworks.ca/2018/
I don't think we need to reproduce the same information on the main page.

**Comment by dcwalk** [comment]
I'm inclined to favour not adding this. 

The info is in the full CFP, as Ben mentioned, and as I'm distributing in networks I'm adding framing text to that effect (e.g. we have an upcoming open call to talk about proposals!)-- assume you all are doing likewise!

**Review by dcwalk — COMMENTED** [review]
See comments, I'm inclined to leave the text as is

**Comment by patcon** [comment]
For my own clarity and sync-up: what's the shortlist of imagined user personas that we each think would be rad to come to this? To speak in it?

(Happy to share my own too!)

Sorry to go back to basics :heart:

**Comment by dcwalk** [comment]
@patcon -- I'm wondering two things:

1) given timing, if we want to imagine that for participants only rather than speakers?
2) could we have this conversation in the planning repo rather than a PR? It feels more suited there!

**Comment by dcwalk** [comment]
Are we okay to close this at the call will only be up for another week?

**Comment by dcwalk** [comment]
Okay, I'm closing, let's reopen if needed!

**Pull request closed without merging**
