### PR TITLE
Update email signup 

### PR DESCRIPTION
**Pull request by dcwalk**
Updated the email signup to redirect to mailman. This changes the form success condition significantly. 

@garrying do you have thoughts on the best way to account for that?

### CODE REVIEW

**Comment by dcwalk** [comment]
Travis is failing on on ipfs gateway 😱

**Comment by garrying** [comment]
@dcwalk I made a quick edit to the `Subscribe results page` on the listserve so that there's a clear link back to the site after submit. We could do a `meta` redirect replicating what we had with Formspee, but we'd need to adjust the banner wording to account for the confirmation step.

screen shot 2018-10-28 at 5 25 28 pm

Thinking we could come back to improving this with the next version.

**Comment by garrying** [comment]
Any issues/thought with the change? I also included a minor fix for the container padding with c4c9a11

**Comment by dcwalk** [comment]
This looks great @garrying! sorry for not responding sooner. It seems like we are happy to merge now?

**Comment by garrying** [comment]
This hasn't been deployed yet. URL tests are failing on `master` after merge: https://travis-ci.org/ournetworks/ournetworks.ca/builds/455337704

**Pull request merged**
