### PR TITLE
September Design Update #3

### PR DESCRIPTION
**Pull request by garrying**
Carried over from #133 

## Fixes
- [x] Opaque session blocks -> 39f6d47
- [x] Copy edit on `/accessibility` -> 677cbc0 -> d06f447413c05e12c1f306cfb6609631d75280ed
- [x] Copy fixes on `/environment` -> 574aed300aabb21774cf24373dc86af5cce8556c
- [x] Copy fixes on `/visiting` -> 21779f3
- [x] `Outdoor Screening` -> `Outdoor screening` 0d14b56

## Features

- [x] Remove Open hour block -> 4cb3ee2
- [ ] refine zine library page
  - [ ] form refinement (mailing address, note formatting (use of small), deadline (open call until conf)) @thinkbulecount2
- [x] add childcare and presenter info on accessibility -> 62a658b 
- [x] add content on environment @dcwalk
  - [x] add mention of Global Climate Strike on program -> b8fa18ae1eebc7eb8164345218edacfbaf5f2962
- [x] Add keynote -> 6cbc55a8f71f5b73d47392f0e3c0e97e736aa099
  - [ ] Add image?
- [x] Extend lightning talks aft slot 30 mins -> c8c5fb96dbff8420a6fc93139f72eca42bfb0139
- [x] Mesh lightning talks  -> e34ce1e0fb4e58c78f031f44b75fc582c2d11dce
- [x] Add Screenprint our swag sessions -> 4633b8d

### CODE REVIEW

**Comment by dcwalk** [comment]
@garrying is there a way to gracefully handle overlaps on program? see below, but also I think for other events (screenprinting) this would be useful!

Screenshot_2019-09-12_21-24-51

**Comment by dcwalk** [comment]
ping @garrying to re-pick this up!

**Comment by garrying** [comment]
> @garrying is there a way to gracefully handle overlaps on program? see below, but also I think for other events (screenprinting) this would be useful!

Added a new `.overlap` class with `.session-block` to treat these cases. They'll be 80% opaque.

**Review by dcwalk — APPROVED** [review]
Great, thanks for the 'uge cleanup

**Comment by dcwalk** [comment]
Okay, slightly a shotgun merge but I want to have stuff live for emails this aft/tomorrow!

**Pull request merged**
