### PR TITLE
June Design Update

### PR DESCRIPTION
**Pull request by garrying**
- [x] Add accent colour
- [x] Add Nimbus Sans l
- [x] Implementation of responsive font-size Sass mix-in
- [x] Implementation of outline text Sass mix-in
- [x] Updated button styles (First pass)

## From June 22 call

- [x] Revise layout to align more with the horizontal sectioning
- [x] Design attribution (43a2f4a)
- [x] Update social image (https://github.com/ournetworks/ournetworks.ca/blob/master/images/social.png)
  - [x] @garrying to create `1050px` by `550px` PNG asset
  - social
- Homepage
  - [x] Revise top nav to be less prominent
    - [x] @thinkbulecount2 research a media query, or ARIA, to tell if someone is using a screenreader
  - [x] Typographic moment for `RE:..`
    - @thinkbulecount2 looking at implementing https://github.com/crccheck/text-mix.js
- Update style of announcements banner
  - [x] Update css of https://github.com/ournetworks/ournetworks.ca/blob/master/_sass/_announcements.scss
- Resolve the Quotes block on the current homepage
  - [x] Remove quotes from homepage
  - [x] New placement(s) of quotes
    - @garrying find a way to include in footer?
- Resolve Recorded Talks page
  - [x] Decide on placement
    - Removing from navigation for now
  - ~[x] Navigation element to get to page~
- Resolve Meetup page
  - [x] Decide on placement
    - Remove for now
  - ~[x] Navigation element to get to page~

### Stretch
- [ ] Mention TMAC venue
- [ ] Add in vector clip-art assets
- [x] Update Sponsors 
  - [x] Remove unconfirmed > here: https://github.com/ournetworks/ournetworks.ca/pull/102/commits/c39b547051a19dd0cdb8eefa8744995a0791a8ea
  - [x] Add MOSS logo svg
  - [x] Add MOSS logo to sponsors list > started here: https://github.com/ournetworks/ournetworks.ca/pull/102/commits/e4868c032590183a6e7ecde7c1f8dba6a1098750
- [ ] Revise open hours to only display upcoming ones
- [ ] Revise/include organizer bios

### CODE REVIEW

**Comment by dcwalk** [comment]
Hey, really starting to come together! Just some basic thoughts (I'll try to address the lingering items above too):

Screenshot_2019-06-29_06-16-13

- The contrast of grey font on white background for navigation is _perilously low_ for my shitty dim screen, that makes me think we'll want to adjust colours or increase it for accessibility? 
- Navigation: I'm not against it, but want to make sure I understand: The intent is to have:
   - Global nav in two places: Top Right, Bottom Sticky / Footer;
   - Visible second nav in the Sticky Footer (like the look!)
   - Then a sort of tertiary (?) nav in Footer for subdomains: previous years for now

I think the nav works, just think we might want to treat content a little differently this year for the global nav/secondary... like move everything off "About" and have only secondary pages, same for anything that has more than one subpage.

---

- Placement of quotes: I was JUST THINKING before reading your comment @garrying, that it would be cool if we could slowly keep adding the quotes to the footer at the bottom of the page :))), so yeah +1 on that :tada: 
- Placement of meetup page: could we consider putting it in the footer? I think it could be under twitter or similar to the Previous Years.
- Meetup page: I was imagining we could re-boot this as a splash page "Next meetup is" sort of thing and link to the places to find out about it. So a subdomain works well enough :woman_shrugging: I'd be happy to follow up on this in a new PR
- We are good for our 3 main sponsors right now! I can crib the sponsor page from last year...?

**Comment by benhylau** [comment]
Looking great! Comments:

- Love the Sticky Footer secondary nav in `>`
- Lines around feel unnecessary
    ```
    ------------------------------------
    Previous Years > 2017 2018
    ------------------------------------
    ```
    Perhaps even same line as `Previous Years > 2017 2018 // Twitter > @_ournetworks` to make space for typing text
- **SUPPORT US** can probably be collapsed to **ABOUT** once we have more Sticky Footers?
- Apply alpha orange overlay on video instead of grey 😉  
- Feel having two navs (Sticky Footers & top right) is redundant

**Comment by garrying** [comment]
@dcwalk Thanks for the feedback and sponsors commits! The intent with navigation is right—it's a little redundant and worth a revisit in a later phase. I moved the quotes to the bottom and added a link to the meetup.com page. Thinking we can swap the link when we get to revising the page.

@benhylau I agree with the footer. Revised it to be terminal-like with the `>`s now that quotes are in there.

**Comment by dcwalk** [comment]
Looking nice! Love that brickwork :grin: 

I feel like we should change the code to only show upcoming open hours on the mainpage, but that is not a block, I edited/added to stretch goal

**Comment by dcwalk** [comment]
Looks like there is that single typographic element we're looking to land and then we are good to go? :tada:

**Review by mylonelycomputer — APPROVED** [review]
Looks good to me!

**Comment by ana0** [comment]
Wanna check that the way this is getting cut off is intentional?

Screenshot_2019-06-30 Our Networks

And that the scrolling/typing anim on the 2nd para here is gone now?

Screenshot_2019-06-30 Our Networks(1)

**Comment by garrying** [comment]
@ana0 The footer cropping is intentional and the typing block in 2nd paragraph was moved to the footer

**Review by dcwalk — APPROVED** [review]

**Pull request merged**
