### PR TITLE
add events type and cfp open hours calls

### PR DESCRIPTION
**Pull request by dcwalk**
This is a preliminary implementation that addresses https://github.com/ournetworks/2018/issues/32, however there are a couple open questions

- embed events on first page using _includes?
- custom post or data for events? (especially imagining their display (embedded) rather than as a new page)

TODO:
- [x] have events show up on first page
- [x] test buttons
- [x] fix icon rendering on buttons?
- [x] correct ics

### CODE REVIEW

**Comment by dcwalk** [comment]
Hey @garrying I've gotten this in much better shape, went with data to implement "calls" (maybe a bit hack-y), but also I think using data as a way to handle sessions probably makes the most sense down the road...? Had thoughts about a calendar, maybe modal description info... does that sound horrible enough?

Anyway, your eyes on fixing the icons would be appreciated!

**Comment by garrying** [comment]
@dcwalk Include icon and layout fixes in 50416f4. ~~There's an issue with having multiple ICS buttons on a page in that the JS will create a file using info from the last instance of the button on a page. Could we make two ICS files for now?~~

Using data is cool with me. I find collections a bit easier to deal with in terms of inline styling of content. We can probably swap over without issue if we have second thoughts later.

**Comment by garrying** [comment]
Ignore that note about the ICS issue. Fixed in 677683b

**Comment by dcwalk** [comment]
Thanks @garrying -- looking good! yeah I (at least partially) mucked up the ics by not incl. the js, but wouldn't have gotten it working!

**Comment by dcwalk** [comment]
Just tested and everything looks good to me! Can we merge?
....and deploy?

**Comment by garrying** [comment]
Added a small formatting edit. Yeah, we can merge and deploy.

**Comment by dcwalk** [comment]
Want the honours? 🎉 🎉 🎉

**Pull request merged**
