### PR TITLE
Tag all sessions

### PR DESCRIPTION
**Pull request by ana0**

### CODE REVIEW

**Review by RangerMauve — APPROVED** [review]
LGTM

**Comment by dcwalk** [comment]
Down with this (I see @garrying is doing some work), only thing I'd ask is if we can perhaps change the colour intensity or something to make clear the distinction between  unmoderated <-> moderated?

**Review by garrying — APPROVED** [review]
Added minor sessionID revert bb8ec50. +1 to colour to distinguish mod

**Comment by ana0** [comment]
Merging and will do colour changes as a stretch goal

**Pull request merged**
