### PR TITLE
fix my bio

### PR DESCRIPTION
**Pull request by jtracey**

### CODE REVIEW

**Comment by dcwalk** [comment]
Thanks @jtracey this looks good! (And apologies for the mistake!)

 It looks like we are having an issue with our build process so I'm going to poke about a bit before merging.

**Comment by dcwalk** [comment]
Hmm, @garrying and @patcon-- so after checking around on `iv undefined`, from all that I can tell and checking on travis the vars are still there... I tried closing and reopening, and triggering a rebuild.

I'm wondering if it is because @jtracey is from outside the org and has opened? Will test in a new branch shortly to see 🤷‍♀️ Sorry, travis and CI not my strong suit.

**Comment by dcwalk** [comment]
Hey @jtracey, it appears there is some issue with our testing when PRs are launched from outside the repo, I've move your changes to here #54 mostly because I'm worried the site won't get correctly built+deployed if the CI fails.

🙏

**Comment by dcwalk** [comment]
Okay it is fixed! Sorry for the run around, gonna close this PR

screen shot 2018-06-28 at 9 28 23 pm

**Comment by garrying** [comment]
Hey! Sorry for the hassle. There is a missing condition with the Travis CI build for incoming PRs from forked repos; missing check if encrypted environment variables are present. I believe it should deploy, with the environment variables present, when merged to `master`.

Referenced in the build: https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions.

**Comment by dcwalk** [comment]
Thanks garry for deets! Makes sense, I'm going to open an issue to hash out how we want to address this : #55

**Pull request closed without merging**
